import streamlit as st
import edge_tts
import asyncio
import shutil
import os
from gradio_client import Client # <--- The Magic Bridge
from streamlit_mic_recorder import mic_recorder

# ==========================================
# 1. CONFIGURATION & THEME
# ==========================================
st.set_page_config(page_title="VANI", page_icon="🎙️", layout="wide")

# Royal Theme CSS
st.markdown("""
<style>
    .stApp {
        background: linear-gradient(to bottom right, #001540, #002d72, #001540);
        color: white;
    }
    .stTextInput > div > div > input, .stTextArea > div > div > textarea {
        background-color: rgba(0, 20, 60, 0.6);
        color: white;
        border: 1px solid #D60000;
    }
    div.stButton > button {
        background: linear-gradient(90deg, #D60000, #ff4d4d);
        border: none;
        color: white;
        font-weight: bold;
    }
    .footer {
        position: fixed; left: 0; bottom: 0; width: 100%;
        background: rgba(0, 21, 64, 0.95);
        color: rgba(255,255,255,0.7); text-align: center;
        padding: 10px; font-size: 11px;
    }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
async def generate_edge_audio(text, voice):
    output_file = "vani_std.mp3"
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(output_file)
    return output_file

def clone_with_gradio(text, speaker_wav_path):
    """
    Connects to the Coqui XTTS Space on Hugging Face.
    This runs on their GPU, not yours.
    """
    try:
        # We connect to the official Coqui XTTS Space
        client = Client("coqui/xtts")
        
        # We send the request
        result = client.predict(
            prompt=text,
            language="en",
            audio_file_pth=speaker_wav_path,
            mic_file_path=None,
            use_mic=False,
            voice_cleanup=False,
            no_lang_auto_detect=False,
            agree=True,
            api_name="/predict"
        )
        # result[1] usually contains the path to the downloaded audio file
        return result[1]
    except Exception as e:
        return f"Error: {e}"

# ==========================================
# 3. MAIN UI
# ==========================================
st.title(" VANI ")
st.markdown("### Serverless Neural Engine")

tab_std, tab_clone = st.tabs([" Vani (Standard)", "🧬 God Mode (Serverless)"])

# === TAB 1: STANDARD (EdgeTTS) ===
with tab_std:
    st.markdown("<br>", unsafe_allow_html=True)
    c1, c2 = st.columns([2, 1])
    with c1:
        txt = st.text_area("Script", "Hello, this is the standard engine.")
    with c2:
        voice = st.selectbox("Voice", ["en-US-GuyNeural", "en-IN-NeerjaNeural", "en-GB-SoniaNeural"])
        if st.button("Generate Standard"):
            out = asyncio.run(generate_edge_audio(txt, voice))
            st.audio(out)

# === TAB 2: GOD MODE (Hugging Face Bridge) ===
with tab_clone:
    st.markdown("<br>", unsafe_allow_html=True)
    
    col_rec, col_gen = st.columns(2)
    
    with col_rec:
        st.markdown("#### 1. Input Voice")
        st.info("Record a clear 5-10 second sample.")
        audio = mic_recorder(start_prompt="🔴 Record", stop_prompt="⏹️ Stop", key='recorder')
        
        # Save audio to a real file so Gradio can read it
        if audio:
            with open("my_voice_sample.wav", "wb") as f:
                f.write(audio['bytes'])
            st.audio(audio['bytes'])
            st.success("Sample Saved as 'my_voice_sample.wav'")

    with col_gen:
        st.markdown("#### 2. Neural Synthesis")
        clone_text = st.text_area("What should I say?", "This audio is generated by connecting to Hugging Face servers remotely.")
        
        if st.button("🧬 GENERATE CLONE"):
            if audio and clone_text:
                with st.spinner("Connecting to Coqui Cloud (Wait 10-20s)..."):
                    # Check if file exists
                    if os.path.exists("my_voice_sample.wav"):
                        output_path = clone_with_gradio(clone_text, "my_voice_sample.wav")
                        
                        if "Error" in output_path:
                            st.error(output_path)
                            st.warning("Note: If the server is busy, try again in 1 minute.")
                        else:
                            st.success("✅ Synthesis Complete")
                            st.audio(output_path)
                    else:
                        st.error("Please record audio first.")
            else:
                st.error("Missing audio or text.")

# FOOTER
st.markdown("""
<div class="footer">
    POWERED BY SAMRION INTELLIGENCE | © 2026 SAMRION AI INFRASTRUCTURE | FOUNDER: NITIN RAJ
</div>
""", unsafe_allow_html=True)
